### ISSUE TITLE
[BUG] Embeds not working - Invidious Error

### ISSUE THREAD

**Issue by Kyrela** [iGerman00/koutube#10]
# Description

Since a couple of hours, the koutube stopped working in Discord. An embed is correctly created, but it displays
> Invidious Error
> Please sign in

![image](https://github.com/user-attachments/assets/954b9ce3-8854-4a05-a48c-9056d5bdce29)

Seems to be reproductible on any youtube video.

**Comment by iGerman00** [comment]
Not a koutube issue, I can't fix it. Track https://github.com/iv-org/invidious issues.

**Comment by iGerman00** [comment]
I'm not sure how long this will last but I made Invidious work again. Might break at any moment because YouTube is actively fighting against this.
