### ISSUE TITLE
YT Video not showing up

### ISSUE THREAD

**Issue by x-FBi** [iGerman00/koutube#13]
Hello,
someone posted this in a discord and nothing was returned by koutu.be
[https://www.youtube.com/watch?v=RAmEzMZol8o](url)
Here's what I tried:

- https://koutu.be/view/watch?v=RAmEzMZol8o
- https://koutu.be/view/watch?v=RAmEzMZol8o&nocache
- https://koutu.be/watch?v=RAmEzMZol8o&nocache
- https://koutu.be/watch?v=RAmEzMZol8o&nocache&stock

https://koutu.be/img/watch?v=RAmEzMZol8o Did work.

Link: https://music.youtube.com/watch?v=yrYJlSHsf24
https://music.koutube.com/watch?v=yrYJlSHsf24
Did not show up as expected.

**Comment by iGerman00** [comment]
#12 
TLDR: video too long for Discord
