### ISSUE TITLE
Could you turn it seekable on mobile?

### ISSUE THREAD

**Issue by kabegithub** [iGerman00/koutube#2]
I found a issue I can’t be seeking on iOS discord client. Could you solve this issue?

**Comment by iGerman00** [comment]
As far as I know, that is not controlled by YocksTube, so I can't fix it

**Comment by iGerman00** [comment]
Further investigation led me to conclude that this is a bug with Discord's mobile clients. I have reported it to their team. It may have something to do with the number of redirects such a video link requires to work, maybe the iOS client gets confused as to whether or not it's a video or not.

To reproduce without using my service, you can use a direct iteroni link:
```
https://iteroni.com/latest_version?id=dQw4w9WgXcQ&itag=22
```

**Comment by kabegithub** [comment]
@iGerman00 I tested with iternoni link but I cannot seek on discord ios.
It recognize as image so I think I need wait to fix by discord.
The direct link as like this

`https://images-ext-1.discordapp.net/external/vyyOUT3RwaT0LI2q_U9vOvLM39yJyDqyyAwuXsmNg1A/%3Fid%3DdQw4w9WgXcQ%26itag%3D22/https/iteroni.com/latest_version?format=jpeg`

**Comment by iGerman00** [comment]
The iteroni link was to prove its not Yockstube's problem

**Comment by iGerman00** [comment]
This has been reported to Discord, nothing else I can do.
