### ISSUE TITLE
Idea: optional DeArrow support?

### ISSUE THREAD

**Issue by tkukec** [iGerman00/koutube#3]
I really like [dearrow](https://dearrow.ajay.app/)

I watch a great video, and send it to a friend, only for it to turn into clickbait garbage

A koutube flag to pull the title/thumbnail from the dearrow API would be great. 

<sup>if you're not interested in implementing it, i can do it myself in a few weeks (after finals)</sup>

See for example:
![image](https://github.com/iGerman00/koutube/assets/63642309/e6941918-4c6f-4a68-9dc0-ac21918baed8)
![image](https://github.com/iGerman00/koutube/assets/63642309/ca5a8d79-1190-46fa-a65f-dd2d0d3a94e4)

**Comment by iGerman00** [comment]
Completed in https://github.com/iGerman00/koutube/commit/100f89f78a093ce421b7412167ba165d6f026fa4
