### ISSUE TITLE
Some video fail to embed on discord 

### ISSUE THREAD

**Issue by RoyRiv3r** [iGerman00/koutube#4]
Ex: [https://koutu.be/watch?v=LE4KrMMRKIo](https://koutu.be/watch?v=LE4KrMMRKIo)
![image](https://github.com/user-attachments/assets/e91d0f4e-98d0-4e9f-aad9-3650dbab5618)

**Comment by RoyRiv3r** [comment]
Doesn't render
https://koutu.be/watch?v=8hBmepWUJoc&dearrow
for
https://www.youtube.com/live/8hBmepWUJoc

**Comment by iGerman00** [comment]
That's due to the fact that the Invidious server that I host is in Germany, and by default many official artist channel uploads (like songs and such) are just not embeddable and don't return a video. I can't fix it right now as I don't have a server elsewhere.
