### ISSUE TITLE
Invidious Error

### ISSUE THREAD

**Issue by DubyaDude** [iGerman00/koutube#6]
As of late, koutube has been returning 'Invidious Error' for the embed.

Sample URLs used:
https://www.koutube.com/watch?v=8XP47iCJlJk
https://www.koutube.com/watch?v=hwomEQfD0UU
![image](https://github.com/user-attachments/assets/1c5f8a8c-a9fb-47b9-a60a-97781ffb742c)

**Comment by iGerman00** [comment]
This isn’t fixable by Koutube, it’s an Invidious issue. https://github.com/iv-org/invidious/issues/4734#issuecomment-2268996911
