### ISSUE TITLE
[BUG] embeds aren't correct anymore 

### ISSUE THREAD

**Issue by EDM115** [iGerman00/koutube#8]
I know YouTube is doing some fuckery for blocking ai scrappers and it affects a lot of projects  
just saying that it doesn't embed the video anymore, just a small thumbnail of it

**Comment by iGerman00** [comment]
This depends on whether or not Invidious is working and whether or not the video is available in Germany. There's not much I can do to fix it.

**Comment by EDM115** [comment]
what about link that used to work but doesn't embed correctly anymore ?

**Comment by iGerman00** [comment]
As I said, it's either/or. I've recently refreshed the invidious token so try again now

**Comment by EDM115** [comment]
it indeed works ❤️
