### ISSUE TITLE
[BUG] Does not work with posts

### ISSUE THREAD

**Issue by EDM115** [iGerman00/koutube#9]
It surprisingly works with channels but not posts.  
Ex : http://www.youtube.com/post/UgkxfxipldNQ4CzpevELraNYKYkg-I1NI9CR -> http://koutube.com/post/UgkxfxipldNQ4CzpevELraNYKYkg-I1NI9CR  
it displays "[Invidious Error](http://koutube.com/post/UgkxfxipldNQ4CzpevELraNYKYkg-I1NI9CR)  
Video unavailable"

**Comment by iGerman00** [comment]
As per the [Invidious API](https://docs.invidious.io/api/), posts are currently not supported. I'll only be able to add support for posts if they start supporting them.

**Comment by EDM115** [comment]
my bad
